fix moesif data collector
wso2/apim-analytics-publisher pull request #107
Opened 2023-10-25 07:35 UTC by tharindu1st

fix moesif data collector

2023-10-25 07:51 UTC, tishan89 requested changes

2023-10-25 07:51 UTC, tishan89 commented on component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/retriever/ConfigBaseMoesifKeyRetriever.java
> +package org.wso2.am.analytics.publisher.retriever;
license

2023-10-25 07:51 UTC, tishan89 commented on component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/GenericInputValidator.java
> +                    new AbstractMap.SimpleImmutableEntry<>(ORGANIZATION_ID, String.class),
Please make sure there new attributes are set by MI to the builder. Else publishing will fail for even the Choreo flow

2023-10-26 04:26 UTC, ruks commented on component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/GenericInputValidator.java
>      private static final Map<String, Class> defaultResponseEventSchema = Stream.of(
Are we adding these new attributes only for moseif? or same published for choreo as well?

2023-10-26 12:34 UTC, closed without merging

2023-10-26 12:34 UTC, tharindu1st commented
Closing this pr with https://github.com/wso2/apk/pull/1834